const fs = require('fs');

const path = './src/data/schemes.json';
const schemes = JSON.parse(fs.readFileSync(path, 'utf8'));

const newSchemes = [
  // TAMIL NADU
  {
    "id": "tn-010",
    "state": "TN",
    "state_name": "Tamil Nadu",
    "name_en": "Chief Minister's Breakfast Scheme",
    "name_local": "முதலமைச்சரின் காலை உணவுத் திட்டம்",
    "category": "Education",
    "min_age": 5,
    "max_age": 10,
    "income_limit": 1000000,
    "occupations": ["Student", "All"],
    "eligibility": "Students of Class 1 to 5 in government schools",
    "benefit": "Free nutritious breakfast on all working school days",
    "documents": ["School ID Card", "Aadhaar Card"],
    "steps": ["Enroll in government primary school", "Breakfast is served automatically"],
    "link": "https://tn.gov.in/breakfast",
    "description_en": "Nutritious breakfast for primary school children to improve health and attendance",
    "description_local": "தொடக்கப் பள்ளி குழந்தைகளுக்கு சத்தான காலை உணவு"
  },
  {
    "id": "tn-011",
    "state": "TN",
    "state_name": "Tamil Nadu",
    "name_en": "Makkalai Thedi Maruthuvam",
    "name_local": "மக்களை தேடி மருத்துவம்",
    "category": "Health",
    "min_age": 45,
    "max_age": 100,
    "income_limit": 1000000,
    "occupations": ["Senior Citizen", "Homemaker", "All"],
    "eligibility": "Patients above 45 years with non-communicable diseases",
    "benefit": "Doorstep delivery of medicines and healthcare services",
    "documents": ["Aadhaar Card", "Medical Records"],
    "steps": ["Register at local PHC", "Health worker visits home", "Receive free medicines directly"],
    "link": "https://mtm.ihmctn.com/",
    "description_en": "Home delivery of medicines for chronic diseases like diabetes and hypertension",
    "description_local": "நீரிழிவு போன்ற நோய்களுக்கான மருந்துகளை வீடுகளுக்கே சென்று வழங்குதல்"
  },
  {
    "id": "tn-012",
    "state": "TN",
    "state_name": "Tamil Nadu",
    "name_en": "Innuyir Kappom - Nammai Kaakkum 48",
    "name_local": "இன்னுயிர் காப்போம் - நம்மை காக்கும் 48",
    "category": "Health",
    "min_age": 0,
    "max_age": 100,
    "income_limit": 1000000,
    "occupations": ["All"],
    "eligibility": "Road accident victims within Tamil Nadu borders",
    "benefit": "Free emergency medical treatment up to ₹1,00,000 for the first 48 hours",
    "documents": ["None required during emergency"],
    "steps": ["Admit accident victim to empaneled hospital", "Treatment begins immediately without upfront cost"],
    "link": "https://tnhealth.tn.gov.in",
    "description_en": "Free emergency medical treatment for road accident victims in the golden hour",
    "description_local": "சாலை விபத்தில் பாதிக்கப்பட்டவர்களுக்கு முதல் 48 மணிநேர இலவச சிகிச்சை"
  },
  {
    "id": "tn-013",
    "state": "TN",
    "state_name": "Tamil Nadu",
    "name_en": "Naan Mudhalvan Scheme",
    "name_local": "நான் முதல்வன் திட்டம்",
    "category": "Skill Development",
    "min_age": 16,
    "max_age": 25,
    "income_limit": 1000000,
    "occupations": ["Student", "Unemployed"],
    "eligibility": "School and college students in Tamil Nadu",
    "benefit": "Free industry-relevant skill training and career guidance",
    "documents": ["Student ID", "Aadhaar Card"],
    "steps": ["Register on Naan Mudhalvan portal", "Take psychometric test", "Enroll in specialized courses", "Attend corporate training"],
    "link": "https://www.naanmudhalvan.tn.gov.in/",
    "description_en": "Skill enhancement and career guidance initiative for youth",
    "description_local": "இளைஞர்களுக்கான திறன் மேம்பாடு மற்றும் தொழில் வழிகாட்டுதல்"
  },
  {
    "id": "tn-014",
    "state": "TN",
    "state_name": "Tamil Nadu",
    "name_en": "Dr. Muthulakshmi Reddy Maternity Benefit",
    "name_local": "டாக்டர் முத்துலட்சுமி ரெட்டி மகப்பேறு நிதி உதவி",
    "category": "Women Empowerment",
    "min_age": 19,
    "max_age": 45,
    "income_limit": 200000,
    "occupations": ["Homemaker", "Worker", "All"],
    "eligibility": "Pregnant women aged 19 and above below poverty line (for first 2 deliveries)",
    "benefit": "₹18,000 financial assistance and nutrition kits",
    "documents": ["PICME Registration Number", "Aadhaar Card", "Bank Passbook"],
    "steps": ["Register pregnancy on PICME", "Visit Village Health Nurse", "Receive installments in bank account"],
    "link": "https://picme.tn.gov.in",
    "description_en": "Financial assistance for pregnant women to ensure proper nutrition",
    "description_local": "கர்ப்பிணிப் பெண்களுக்கு ஊட்டச்சத்தை உறுதி செய்வதற்கான ஆர்த்திக உதவி"
  },
  {
    "id": "tn-015",
    "state": "TN",
    "state_name": "Tamil Nadu",
    "name_en": "Thamizhagam Rural Housing Scheme",
    "name_local": "தமிழக ஊரக வீட்டு வசதி திட்டம்",
    "category": "Housing",
    "min_age": 18,
    "max_age": 70,
    "income_limit": 250000,
    "occupations": ["Worker", "All"],
    "eligibility": "Homeless poor families in rural block panchayats",
    "benefit": "₹2,10,000 total subsidy for pucca house construction",
    "documents": ["Land Patta", "Aadhaar Card", "Ration Card", "Income Certificate"],
    "steps": ["Apply via Gram Panchayat", "Submit land documents", "Approval by BDO", "Construction linked installments"],
    "link": "https://tnrd.tn.gov.in",
    "description_en": "Scheme providing financial aid to build concrete houses in rural areas",
    "description_local": "ஊரக பகுதிகளில் கான்கிரீட் வீடுகள் கட்ட நிதி உதவி"
  },

  // ANDHRA PRADESH
  {
    "id": "ap-008",
    "state": "AP",
    "state_name": "Andhra Pradesh",
    "name_en": "YSR Vahana Mitra",
    "name_local": "వైఎస్ఆర్ వాహన మిత్ర",
    "category": "Employment",
    "min_age": 18,
    "max_age": 65,
    "income_limit": 300000,
    "occupations": ["Self-Employed", "Worker"],
    "eligibility": "Auto/Taxi/Cab drivers who own their vehicles",
    "benefit": "₹10,000 per year for vehicle maintenance and insurance",
    "documents": ["Vehicle RC", "Driving License", "Aadhaar Card", "Bank Passbook"],
    "steps": ["Apply on Navasakam portal", "Submit DL and RC proof", "Verification by transport department", "Annual direct transfer"],
    "link": "https://navasakam.ap.gov.in/vahanamitra",
    "description_en": "Financial assistance for auto and taxi drivers",
    "description_local": "ఆటో, టాక్సీ డ్రైవర్లకు ఆర్థిక సహాయం"
  },
  {
    "id": "ap-009",
    "state": "AP",
    "state_name": "Andhra Pradesh",
    "name_en": "YSR Matsyakara Bharosa",
    "name_local": "వైఎస్ఆర్ మత్స్యకార భరోసా",
    "category": "Agriculture", // Fisheries related
    "min_age": 18,
    "max_age": 65,
    "income_limit": 500000,
    "occupations": ["Worker", "Self-Employed"],
    "eligibility": "Active traditional and mechanized boat fishermen",
    "benefit": "₹10,000 per year during the marine fishing ban period",
    "documents": ["Fisherman ID", "Aadhaar Card", "Bank Passbook"],
    "steps": ["Register with Fisheries Department", "Submit boat/license details", "Direct credit during ban period"],
    "link": "https://ap.gov.in/matsyakara",
    "description_en": "Financial relief for fishermen during non-fishing ban season",
    "description_local": "వేట నిషేధ సమయంలో మత్స్యకారులకు ఆర్థిక సహాయం"
  },
  {
    "id": "ap-010",
    "state": "AP",
    "state_name": "Andhra Pradesh",
    "name_en": "YSR Nethanna Nestham",
    "name_local": "వైఎస్ఆర్ నేతన్న నేస్తం",
    "category": "Employment",
    "min_age": 18,
    "max_age": 70,
    "income_limit": 300000,
    "occupations": ["Worker", "Self-Employed"],
    "eligibility": "Handloom weaver families owning at least one handloom",
    "benefit": "₹24,000 per year for upgrading equipment",
    "documents": ["Weaver ID", "Aadhaar Card", "Bank Passbook"],
    "steps": ["Apply at Ward Secretariat", "Verification of handloom ownership", "Direct transfer to bank account"],
    "link": "https://ap.gov.in/nethanna",
    "description_en": "Financial assistance to handloom weavers for modernization",
    "description_local": "చేనేత కార్మికులకు ఆర్థిక సహాయం"
  },
  {
    "id": "ap-011",
    "state": "AP",
    "state_name": "Andhra Pradesh",
    "name_en": "Jagananna Vasathi Deevena",
    "name_local": "జగనన్న వసతి దీవెన",
    "category": "Education",
    "min_age": 16,
    "max_age": 25,
    "income_limit": 250000,
    "occupations": ["Student"],
    "eligibility": "Students pursuing ITI, Polytechnic, or Degree courses",
    "benefit": "₹10,000 to ₹20,000 per year for hostel and mess charges",
    "documents": ["College ID", "Aadhaar Card", "Income Certificate"],
    "steps": ["Apply via college administration", "Submit income and caste certs", "Amount credited to mother's account"],
    "link": "https://navasakam.ap.gov.in",
    "description_en": "Hostel and mess charge assistance for degree and diploma students",
    "description_local": "విద్యార్థులకు హాస్టల్ మరియు మెస్ ఛార్జీల సహాయం"
  },
  {
    "id": "ap-012",
    "state": "AP",
    "state_name": "Andhra Pradesh",
    "name_en": "YSR Bima",
    "name_local": "వైఎస్ఆర్ బీమా",
    "category": "Social Security",
    "min_age": 18,
    "max_age": 70,
    "income_limit": 250000,
    "occupations": ["Worker", "Farmer", "Unemployed", "All"],
    "eligibility": "Primary breadwinner of BPL families",
    "benefit": "₹5,000,000 accident insurance and ₹1,00,000 natural death relief",
    "documents": ["White Ration Card", "Aadhaar Card", "Nominee Details"],
    "steps": ["Register via village volunteer", "Link bank account", "Claim triggered on casualty"],
    "link": "https://ysrbima.ap.gov.in",
    "description_en": "Comprehensive insurance coverage for primary breadwinners of BPL families",
    "description_local": "బిపిఎల్ కుటుంబాల ప్రధాన సంపాదకులకు సమగ్ర బీమా"
  },
  {
    "id": "ap-013",
    "state": "AP",
    "state_name": "Andhra Pradesh",
    "name_en": "Jagananna Thodu",
    "name_local": "జగనన్న తోడు",
    "category": "Employment",
    "min_age": 18,
    "max_age": 60,
    "income_limit": 500000,
    "occupations": ["Worker", "Self-Employed"],
    "eligibility": "Small street vendors and artisans",
    "benefit": "Interest-free loan of ₹10,000 per year",
    "documents": ["Vending Certificate", "Aadhaar Card", "Bank Account"],
    "steps": ["Apply at Ward Secretariat", "Verification", "Loan disbursement directly to bank"],
    "link": "https://ap.gov.in",
    "description_en": "Interest free loan for small street vendors to boost their business",
    "description_local": "చిరు వ్యాపారులకు వడ్డీ లేని రుణం"
  },

  // KARNATAKA
  {
    "id": "ka-008",
    "state": "KA",
    "state_name": "Karnataka",
    "name_en": "Mathrushree Scheme",
    "name_local": "ಮಾತೃಶ್ರೀ ಯೋಜನೆ",
    "category": "Women Empowerment",
    "min_age": 18,
    "max_age": 45,
    "income_limit": 200000,
    "occupations": ["Homemaker", "Worker", "All"],
    "eligibility": "Pregnant BPL women (for first 2 deliveries)",
    "benefit": "₹6,000 financial aid distributed pre and post delivery",
    "documents": ["Thayi Card", "Aadhaar Card", "BPL Ration Card"],
    "steps": ["Register pregnancy at Anganwadi", "Submit Thayi card", "Aid transferred in installments"],
    "link": "https://dwcd.karnataka.gov.in",
    "description_en": "Maternity benefit for pregnant women in BPL families",
    "description_local": "ಬಿಪಿಎಲ್ ಕುಟುಂಬಗಳ ಗರ್ಭಿಣಿಯರಿಗೆ ಹೆರಿಗೆ ಭತ್ಯೆ"
  },
  {
    "id": "ka-009",
    "state": "KA",
    "state_name": "Karnataka",
    "name_en": "Vidyasiri Scheme",
    "name_local": "ವಿದ್ಯಾಸಿರಿ ಯೋಜನೆ",
    "category": "Education",
    "min_age": 15,
    "max_age": 25,
    "income_limit": 250000,
    "occupations": ["Student"],
    "eligibility": "OBC/SC/ST students pursuing post-matric courses without hostel access",
    "benefit": "₹1,500 per month for accommodation and food for 10 months",
    "documents": ["College Admission Proof", "Caste Certificate", "Income Certificate"],
    "steps": ["Apply on State Scholarship Portal", "Institute verification", "Monthly stipend credited"],
    "link": "https://ssp.postmatric.karnataka.gov.in",
    "description_en": "Food and accommodation stipend for backward class students",
    "description_local": "ಹಿಂದುಳಿದ ವರ್ಗಗಳ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಊಟ ಮತ್ತು ವಸತಿ ಭತ್ಯೆ"
  },
  {
    "id": "ka-010",
    "state": "KA",
    "state_name": "Karnataka",
    "name_en": "Sandhya Suraksha Yojana",
    "name_local": "ಸಂಧ್ಯಾ ಸುರಕ್ಷಾ ಯೋಜನೆ",
    "category": "Social Security",
    "min_age": 65,
    "max_age": 100,
    "income_limit": 20000,
    "occupations": ["Senior Citizen", "Unemployed"],
    "eligibility": "Senior citizens above 65 with income below ₹20,000",
    "benefit": "₹1,200 monthly pension",
    "documents": ["Age Proof", "Income Certificate", "Aadhaar Card", "Bank Passbook"],
    "steps": ["Apply at Nada Kacheri", "Submit age and tax income proof", "Approval by Tahsildar"],
    "link": "https://nadakacheri.karnataka.gov.in",
    "description_en": "Monthly pension scheme for vulnerable senior citizens",
    "description_local": "ದುರ್ಬಲ ಹಿರಿಯ ನಾಗರಿಕರಿಗೆ ಮಾಸಿಕ ಪಿಂಚಣಿ ಯೋಜನೆ"
  },
  {
    "id": "ka-011",
    "state": "KA",
    "state_name": "Karnataka",
    "name_en": "Karnataka Arogya Sanjeevini Scheme",
    "name_local": "ಕರ್ನಾಟಕ ಆರೋಗ್ಯ ಸಂಜೀವಿನಿ",
    "category": "Health",
    "min_age": 0,
    "max_age": 100,
    "income_limit": 0, // State govt employees typically
    "occupations": ["Worker", "Government Employee"],
    "eligibility": "State Government Employees and their dependents",
    "benefit": "Cashless medical treatment in empaneled private hospitals",
    "documents": ["Employee ID", "Dependents Aadhaar Card"],
    "steps": ["Enroll via HRMS portal", "Link family members", "Show e-card at hospital"],
    "link": "https://arogyasanjeevini.karnataka.gov.in",
    "description_en": "Cashless health insurance for Karnataka state government employees",
    "description_local": "ಸರ್ಕಾರಿ ನೌಕರರಿಗೆ ನಗದು ರಹಿತ ಆರೋಗ್ಯ ವಿಮೆ"
  },
  {
    "id": "ka-012",
    "state": "KA",
    "state_name": "Karnataka",
    "name_en": "Chief Minister's Self Employment Scheme",
    "name_local": "ಮುಖ್ಯಮಂತ್ರಿ ಸ್ವಯಂ ಉದ್ಯೋಗ ಯೋಜನೆ",
    "category": "Employment",
    "min_age": 21,
    "max_age": 45,
    "income_limit": 1000000,
    "occupations": ["Unemployed", "Self-Employed", "Worker"],
    "eligibility": "Unemployed youth launching manufacturing/service businesses",
    "benefit": "25-35% margin money subsidy on bank loans up to ₹10 Lakhs",
    "documents": ["Aadhaar Card", "Project Report", "EDP Training Certificate"],
    "steps": ["Apply on CMESA portal", "Submit project report", "Bank Loan Sanction", "Subsidy released"],
    "link": "https://cmegp.kar.nic.in",
    "description_en": "Subsidy support to start a new business or MSME",
    "description_local": "ಹೊಸ ವ್ಯಾಪಾರ ಪ್ರಾರಂಭಿಸಲು ಸಬ್ಸಿಡಿ ಬೆಂಬಲ"
  },
  {
    "id": "ka-013",
    "state": "KA",
    "state_name": "Karnataka",
    "name_en": "Mukhyamantri Raita Vidya Nidhi",
    "name_local": "ಮುಖ್ಯಮಂತ್ರಿ ರೈತ ವಿದ್ಯಾ ನಿಧಿ",
    "category": "Education",
    "min_age": 14,
    "max_age": 25,
    "income_limit": 1000000,
    "occupations": ["Student"],
    "eligibility": "Students who are children of farmers, studying 11th std to post-graduation",
    "benefit": "₹2,000 to ₹11,000 annual scholarship",
    "documents": ["Farmer ID (FID) of Parent", "College Admission Proof", "Aadhaar Card"],
    "steps": ["Apply on e-Governance SSP portal", "Link parent's FID", "Direct transfer to student account"],
    "link": "https://ssp.postmatric.karnataka.gov.in",
    "description_en": "Scholarship for farmer's children pursuing higher education",
    "description_local": "ರೈತರ ಮಕ್ಕಳ ಉನ್ನತ ಶಿಕ್ಷಣಕ್ಕೆ ವಿದ್ಯಾರ್ಥಿವೇತನ"
  },

  // KERALA
  {
    "id": "kl-007",
    "state": "KL",
    "state_name": "Kerala",
    "name_en": "Vidyakiranam Scheme",
    "name_local": "വിദ്യാകിരണം",
    "category": "Education",
    "min_age": 6,
    "max_age": 24,
    "income_limit": 250000,
    "occupations": ["Student"],
    "eligibility": "Children of differently-abled parents",
    "benefit": "Educational assistance from ₹300 per month (school) to ₹1,000 per month (college)",
    "documents": ["Parent's Disability Certificate", "Income Certificate", "School/College enrollment"],
    "steps": ["Apply via Social Justice portal", "Submit disability and income proofs", "Verification by CDPO"],
    "link": "https://sjd.kerala.gov.in",
    "description_en": "Educational assistance to children of parents with severe disabilities",
    "description_local": "ഭിന്നശേഷിക്കാരായ മാതാപിതാക്കളുടെ മക്കൾക്ക് വിദ്യാഭ്യാസ സഹായം"
  },
  {
    "id": "kl-008",
    "state": "KL",
    "state_name": "Kerala",
    "name_en": "Aswasakiranam Scheme",
    "name_local": "ആശ്വാസകിരണം",
    "category": "Social Security",
    "min_age": 18,
    "max_age": 80,
    "income_limit": 100000,
    "occupations": ["Homemaker", "Unemployed", "All"],
    "eligibility": "Caregivers of bedridden, severely disabled, or mentally challenged persons",
    "benefit": "₹600 monthly financial assistance to the caregiver",
    "documents": ["Medical Certificate of Patient", "Aadhaar Card of Caregiver", "BPL Certificate"],
    "steps": ["Apply via Local ICDS office", "Submit medical proofs", "Direct credit to caregiver's bank"],
    "link": "https://sjd.kerala.gov.in",
    "description_en": "Financial aid for caregivers of severely disabled patients",
    "description_local": "കിടപ്പിലായ രോഗികളെ പരിചരിക്കുന്നവർക്കുള്ള ധനസഹായം"
  },
  {
    "id": "kl-009",
    "state": "KL",
    "state_name": "Kerala",
    "name_en": "Karunya Benevolent Fund",
    "name_local": "കാരുണ്യ ബെനവലൻ്റ് ഫണ്ട്",
    "category": "Health",
    "min_age": 0,
    "max_age": 100,
    "income_limit": 300000,
    "occupations": ["All"],
    "eligibility": "BPL and APL families facing catastrophic illnesses (Cancer, Kidney, Heart, Brain)",
    "benefit": "Medical grant up to ₹2,00,000 for critical illness treatment",
    "documents": ["Doctor's Estimate", "Ration Card", "Income Certificate"],
    "steps": ["Submit application at designated hospital", "Approval by Karunya society", "Amount paid directly to hospital"],
    "link": "https://karunya.kerala.gov.in",
    "description_en": "Financial assistance for critical illnesses (Cancer, Cardiac, Kidney)",
    "description_local": "മാരക രോഗങ്ങൾക്കുള്ള സാമ്പത്തിക ചികിത്സാ സഹായം"
  },
  {
    "id": "kl-010",
    "state": "KL",
    "state_name": "Kerala",
    "name_en": "Ayyankali Urban Employment Guarantee Scheme",
    "name_local": "അയ്യങ്കാളി നഗര തൊഴിലുറപ്പ് പദ്ധതി",
    "category": "Employment",
    "min_age": 18,
    "max_age": 65,
    "income_limit": 1000000,
    "occupations": ["Worker", "Unemployed"],
    "eligibility": "Adults residing in urban local bodies willing to do unskilled manual work",
    "benefit": "100 days of guaranteed wage employment per household per year",
    "documents": ["Aadhaar Card", "Bank Account", "Address Proof"],
    "steps": ["Register at Municipality/Corporation", "Get job card", "Apply for work", "Wages credited to bank"],
    "link": "https://kerala.gov.in",
    "description_en": "Guaranteed 100 days of urban employment for unskilled labor",
    "description_local": "നഗരപ്രദേശങ്ങളിലെ തൊഴിലുറപ്പ് പദ്ധതി"
  },
  {
    "id": "kl-011",
    "state": "KL",
    "state_name": "Kerala",
    "name_en": "Subhiksha Keralam",
    "name_local": "സുഭിക്ഷ കേരളം",
    "category": "Agriculture",
    "min_age": 18,
    "max_age": 70,
    "income_limit": 1000000,
    "occupations": ["Farmer"],
    "eligibility": "Farmers and landowners participating in food security agriculture projects",
    "benefit": "Subsidies for integrated farming, seeds, and fertilizer supplies",
    "documents": ["Land Deed", "Aadhaar Card", "Panchayat License"],
    "steps": ["Register on Subhiksha Keralam portal", "Submit farm plan", "Receive agricultural inputs subsidy"],
    "link": "https://subhikshakeralam.kerala.gov.in/",
    "description_en": "Food security scheme offering subsidies for integrated farming",
    "description_local": "സംയോജിത കൃഷിക്കുള്ള സബ്സിഡികൾ നൽകുന്ന ഭക്ഷ്യ സുരക്ഷാ പദ്ധതി"
  },
  {
    "id": "kl-012",
    "state": "KL",
    "state_name": "Kerala",
    "name_en": "Saranya Scheme",
    "name_local": "ശരണ്യ",
    "category": "Employment",
    "min_age": 18,
    "max_age": 55,
    "income_limit": 100000,
    "occupations": ["Women", "Unemployed", "Homemaker"],
    "eligibility": "Widows, divorced, or deserted women starting self-employment",
    "benefit": "Loan up to ₹50,000 with 50% subsidy (up to ₹25,000)",
    "documents": ["Marital Status Certificate", "Income Certificate", "Project Report"],
    "steps": ["Apply at Employment Exchange", "Submit project proposal", "Verification", "Subsidized loan disbursement"],
    "link": "https://employment.kerala.gov.in",
    "description_en": "Self-employment assistance for destitute women and widows",
    "description_local": "വിധവകൾക്കും നിരാലംബരായ സ്ത്രീകൾക്കുമുള്ള സ്വയംതൊഴിൽ സഹായം"
  }
];

const combined = [...schemes, ...newSchemes];
fs.writeFileSync(path, JSON.stringify(combined, null, 2));
console.log('Added ' + newSchemes.length + ' new schemes');
